# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d9ea3b3d7d5e62c04f8549d346668e6dce5242709dd10fc4729bf8bec11c021c04658123738a8b7d1ff67813f17269ba3569030df8b46641da526d6a3b7745f

test:
  secret_key_base: 641ac250eb88dd53a6193c90f900feca0527fbbe8f613923cf891d9880e52d1573c54f03211935791307456c01729af60af1e8c6ede331e9d07a590d5b897b6e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
